name: Build ISO
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y debootstrap xorriso squashfs-tools grub-pc-bin grub-efi-amd64-bin \
            mtools isolinux syslinux-utils casper shim-signed linux-generic calamares lz4
      - name: Build ISO
        run: |
          chmod +x scripts/build-iso.sh
          ./scripts/build-iso.sh
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: king-os-iso
          path: ./*.iso
